### ISSUE TITLE
OOM after a couple of iterations

### ISSUE THREAD

**Issue by siavash-khodadadeh** [tensorflow/agents#20]
I am running DQN on an Atari game (BeamRider-v0). I just get the input image and flatten it and connect it to a fully connected layer with 32 neurons. It runs for 14000 iterations on a Telsa v100 GPU. After 14000 iterations, I get OOM. Is there a memory leak? I am using tf-nightly-gpu-2.0-preview. I have also tried tf-nightly-gpu and the same problem exists. My question is why I don't get the error at the very first iterations? What causes memory usage to grow for 14000 iterations?

**Comment by siavash-khodadadeh** [comment]
I am using almost the same code as in the google codelab documentation. It seems that the problem is happening when I am computing the average return for some reason.

**Comment by PeterZhizhin** [comment]
Maybe your experience replay buffer size is large. This will result in consuming all of your available memory.

**Comment by siavash-khodadadeh** [comment]
@PeterZhizhin Oh, sorry. I forgot to mention that. The buffer size is 100. 
If this was the case, I guess it should have happened in the first 100 iterations. Because after 100 iterations, the size should not increase. I even tried with a buffer size of 2, but the problem still happens.

**Comment by oars** [comment]
Do you have some code to help debug this? We haven't ported the v1 example for Atari yet:
https://github.com/tensorflow/agents/blob/master/tf_agents/agents/dqn/examples/v1/train_eval_atari.py

but it might serve as a good starting point for you as well.

**Comment by siavash-khodadadeh** [comment]
@oars  Thank you so much. I will look at the provided link.
Here is my code:
https://colab.research.google.com/drive/137JrRt2ifwNW51uWL-4osTC1uXM2U9B7

I am getting the error on Google Collab as well as on my own device.
![memory_usage](https://user-images.githubusercontent.com/9966824/54236821-e9f9a980-44ea-11e9-9e5d-a465c6657f76.png)

**Comment by siavash-khodadadeh** [comment]
After some debugging, I guess the problem is from the TFPyEnvironment. 

```
import base64
import imageio
import matplotlib
import matplotlib.pyplot as plt
import PIL.Image
import IPython

import tensorflow as tf

from tf_agents.agents.dqn import dqn_agent
from tf_agents.agents.dqn import q_network
from tf_agents.agents.sac import sac_agent
from tf_agents.drivers import dynamic_step_driver
from tf_agents.environments import suite_gym
from tf_agents.environments import tf_py_environment
from tf_agents.environments import trajectory
from tf_agents.metrics import metric_utils
from tf_agents.metrics import tf_metrics
from tf_agents.policies import random_tf_policy
from tf_agents.replay_buffers import tf_uniform_replay_buffer
from tf_agents.utils import common

tf.compat.v1.enable_v2_behavior()

env_name = 'BeamRider-v0'  # @param


#  Starting the main code

eval_py_env = suite_gym.load(env_name)

eval_env = tf_py_environment.TFPyEnvironment(eval_py_env)

random_policy = random_tf_policy.RandomTFPolicy(
    eval_env.time_step_spec(), 
    eval_env.action_spec()
)


def compute_avg_return(environment, policy, num_episodes=10):
    total_return = 0.0
    for _ in range(num_episodes):
        time_step = environment.reset()
        episode_return = 0.0

        while not time_step.is_last():
            action_step = policy.action(time_step)
            time_step = environment.step(action_step.action)
            episode_return += time_step.reward
        total_return += episode_return

    avg_return = total_return / num_episodes
    return avg_return.numpy()[0]


for iteration in range(10000):
  print(iteration)
  print(compute_avg_return(eval_env, random_policy, 20))
```

The reason is that even this code which does not have anything to do with agents still faces the same problem.

**Comment by sguada** [comment]
Thanks for reducing the problem, it seems that the issue is likely in the TFPyEnvironment, we will look into it.

**Comment by JMorceaux** [comment]
Hi,
I am still having the issue, was it fixed ?
Thanks

**Comment by siavash-khodadadeh** [comment]
To the best of my knowledge, not yet. Here are some ways you can get along with it:
Save your model after a couple of iterations and when you get the OOM, try again.
Make sure that your environment observations are uint8 images which will be take 4x smaller space than float32 and preprocess them for your q learning update. See the Atari example provided by @oars.

**Comment by bayesian** [comment]
ran into the same problem, with pympler profiling, I know that leaked objects are np.ndarray, i.e. the image observations from the environment. 

when we run the environment outside TFPyEnvironment, no memory leaks.

**Comment by bayesian** [comment]
https://github.com/hill-a/stable-baselines/issues/182
root cause is in numpy/pickle which tf_py_environment uses.
 
it works for us when we upgrade numpy to latest version.. verified no more leak.

**Comment by sguada** [comment]
@bayesian could you provide a reproducible examples with TFPyEnvironment and without?

**Comment by sguada** [comment]
Can you check your numpy and TF versions?

**Comment by bayesian** [comment]
our repro example is similar to siavash-khodadadeh gave, only with larger image observations than Atari, thus leaking faster.

as reported in the other link, numpy 1.16.1 fixed the issue.

**Comment by kbanoop** [comment]
Closing this issue, please reopen if you have further questions.
